name= str(input("Enter a Name: "))
age= int(input("Enter your age: "))
location=str(input("Enter your Location: "))
quote=str(input("What is your favorite QUOTE:"))
count = len(quote)
print(" ")
print("Here is your profile summary: ")
print(" ")
print("________________________________________")
print(" ")
print("Welcome", name, "\U0001F923")
print("Age", age)
print(location)
print(quote)
print(count,"character")
print(" ")
print("________________________________________")
